# Generated by Django 6.0 on 2025-12-11 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=500, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Guruh nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Imtihon kodi')),
                ('expired_at', models.DateTimeField(verbose_name='Imtihon tugash vaqti')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.guruh')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.kurs')),
                ('natija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.natija')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(max_length=500, verbose_name='Savol matni')),
                ('variant_a', models.CharField(max_length=255, verbose_name='Variant A')),
                ('variant_b', models.CharField(max_length=255, verbose_name='Variant B')),
                ('variant_c', models.CharField(max_length=255, verbose_name='Variant C')),
                ('variant_d', models.CharField(max_length=255, verbose_name='Variant D')),
                ('javob', models.CharField(choices=[('variant_a', 'variant_a'), ('variant_b', 'variant_b'), ('variant_c', 'variant_c'), ('variant_d', 'variant_d')])),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.kurs')),
            ],
        ),
        migrations.AddField(
            model_name='natija',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.savol'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.exam')),
            ],
        ),
        migrations.AddField(
            model_name='natija',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.student'),
        ),
    ]
