# Generated by Django 6.0 on 2025-12-13 10:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Imtihon kodi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 14, 10, 46, 34, 291317, tzinfo=datetime.timezone.utc), verbose_name='Imtihon tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='natija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.natija'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
