# Generated by Django 6.0 on 2025-12-22 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_exam_code_alter_exam_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 23, 12, 42, 48, 112369, tzinfo=datetime.timezone.utc), verbose_name='Imtihon tugash vaqti'),
        ),
    ]
