# Generated by Django 6.0 on 2025-12-22 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_exam_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 23, 14, 12, 56, 99296, tzinfo=datetime.timezone.utc), verbose_name='Imtihon tugash vaqti'),
        ),
        migrations.RemoveField(
            model_name='savol',
            name='kurs',
        ),
        migrations.AddField(
            model_name='savol',
            name='kurs',
            field=models.ManyToManyField(to='common.kurs', verbose_name='Kurs'),
        ),
    ]
