# Generated by Django 6.0 on 2025-12-22 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_exam_expired_at_remove_savol_kurs_savol_kurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savol',
            name='kurs',
        ),
        migrations.AddField(
            model_name='savol',
            name='exam',
            field=models.ManyToManyField(to='common.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 23, 15, 5, 42, 200969, tzinfo=datetime.timezone.utc), verbose_name='Imtihon tugash vaqti'),
        ),
    ]
